theme: jekyll-theme-minimal
logo: Resources/You.png
title: You Watanabe 好き
description: This is a repository storing handouts and slides mainly for the group presentation. <br /> <br />R. Sham<br />(By the way, Watanabe You is my Waifu.)
