theme: jekyll-theme-minimal
logo: Resources/You.png
title: You Watanabe 好き
description: This is a repository storing handouts and slides for group (or individual) presentations. <br />(By the way, Watanabe You is my Waifu.)
