theme: jekyll-theme-minimal
logo: Resources/You.png
title: You Watanabe 好き
description: This is a simple site for me to store slides mainly for the group presentation. <br />By the way, Watanabe You is my waifu. WTMしゃーばお, 謝謝茄子.
