theme: jekyll-theme-minimal
logo: Resources/SKRS.jpg
title: 萌田薫子好き
description: This is a repository storing handouts and slides for group (or individual) presentations. <br />By the way, Shōjo Kageki Revue Starlight is a masterpiece! <br />And, as for Kaoruko Moeta, she's still my waifu. 
